### ISSUE TITLE
How to include .PNG images

### ISSUE THREAD

**Issue by GasperC** [meslater/MSImageMovieEncoder#1]
I m having problems with -(BOOL)nextFrameInBGRCGBitmapContext:(CGContextRef *)contextRef method. I just dont manage to get it working so it would use array of images. Here is raw code

-(BOOL)nextFrameInBGRCGBitmapContext:(CGContextRef *)contextRef{
    counter++;
    if (counter == 100) {
        return NO;
    }

   // UIImage *image=[UIImage imageNamed:@"imageTest.PNG"];// i just want to use this image for start
    CGContextRef context = *contextRef;
    //CGContextRef context = CGBitmapContextCreate(NULL, image.size.width, image.size.height, 8, 0, CGImageGetColorSpace(image.CGImage), kCGImageAlphaPremultipliedLast);

```
CGContextSetRGBFillColor(context, 0,0,1,1); //RED
CGContextFillRect(context, CGRectMake(0, 0, frameSize.width, frameSize.height));

CGContextSetRGBFillColor(context, 1,0,0,0.5); //BLUE with alpha of 0.5
CGContextFillEllipseInRect(context, CGRectMake(1*counter, 200, 1*counter, 1*counter));
return YES;
```

}

If jou could just fix this example i would appreciate it BIG time.

Did managed to include pictures like this, but colors are just wrong... any ideas?
    CGContextDrawImage(context, CGRectMake(0, 0, frameSize.width, frameSize.height), (image.CGImage));

P.S: Your code is awsome otherwise...:D

**Comment by johndpope** [comment]
at line 115
try this
kCVPixelFormatType_32BGRA > kCVPixelFormatType_32ARGB

**Comment by meslater** [comment]
Sorry for not getting back to you on this, John's reply just came through and reminded me.  Yeah, you just need to change the pixel format.  The reason I have it the way round that I do is because I wasn't using images and BGRA seems to be the native format of the hardware encoder which gives significant performance improvements.
